# Operadores Aritméticos

Los operadores ariméticos se utilizan para realizar operaciones matemáticas sencillas sobre valores numéricos:

1.   Adición
2.   Sustracción
3.   Multiplicación
4.   División
5.   Exponenciación
6.   División de piso
7.   Módulo

## Adición

La operación de suma entre un valor ```a``` y un valor ```b``` se realiza utilizando el operador ```+```: $a + b$

::: {.callout-tip}
Se pueden sumar múltiples valores en una misma expresión. Por ejemplo:  $a + b + c + d$
:::

```{python}
100 + 717.345 + 0
```

## Sustracción

La operación de resta entre un valor ```a``` y un valor ```b``` se realiza utilizando el operador ```-```: $a - b$

::: {.callout-caution}
Nótese que la siguiente operación debería dar un resultado exacto, sin embargo, las computadoras manejan "números de punto flotante" los cuales no poseen una representación binaria de valores limitada y podrían mostrar valores poco precisos.
:::

```{python}
55.54 - 105.54
```

## Multiplicación

Para multiplicar un número **a** y un número **b**, se utiliza el operador **\***.

$a * b$

```{python}
7*2
```

## División

Para dividir un número **a** y un número **b**, se utiliza el operador **/**.

$\frac{a}{b}$

```{python}
15/2
```

## Exponenciación

Para elevar un número **a** al exponente de un número **b**, se utiliza el operador **\****.

$a^b$

```{python}
2**3
```

## Módulo
Para obtener el residuo de la división de un número **a** y un número **b**, se utiliza el operador **%**.

```{python}
6%6
```

```{python}
7%6
```

## División de piso
Para obtener la división de piso de un número **a** y un número **b**, se utiliza el operador **//**.

Funciona de forma similar a la división normal, con la diferencia que retorna un número entero e ignora la parte decimal.

```{python}
10//3
```

## Jerarquía de operaciones
Es importante tener en cuenta la jerarquía de operaciones al utilizar varios operadores aritméticos en una misma expresión.

Las operaciones se efectúan en el siguiente orden:
1.   Expresiones dentro de paréntesis: ()
2.   Exponente: **
3.   Multiplicación, División, División entera, Módulo: *, /, //, %
4.   Suma, Resta: +, -

### Ejemplo

Si quisieramos convertir 100°F a °C. Se utilizaría la siguiente expresión:

$(100 - 32) * 5/9$

Siguiendo la jerarquía de operaciones, se realizan de la siguiente manera:

*   $(100 - 32) * 5/9$
*   $(68) * 5/9$
*   $37.78$


```{python}
(100 - 32) * 5/9
```

Si no se hubieran colocado los paréntesis, obtendríamos un resultado erróneo:
*   $100 - 32 * 5/9$
*   $100 - 32 * 0.5556$
*   $100 - 17.78$
*   $82.22$

```{python}
100 - 32 * 5/9
```
