project:
  type: book

book:
  title: "¡Hola, Python!"
  author: "Diego Morales"
  date: "02/05/2024"
  chapters:
    - index.qmd
    - 01_intro.qmd
    - 02_var.qmd
    - 03_tipos.qmd
    - 04_op_arit.qmd
    - 05_op_asig.qmd
    - 06_op_comp.qmd
    - 07_op_logi.qmd
    - 08_sen_cond.qmd

bibliography: references.bib

format:
  #html:
    #theme: cosmo
  pdf:
    documentclass: scrreprt
lang: es
